name: Update README with Latest Blog

on:
  push:
    branches:
      - main
    paths:
      - README.md

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README with latest blog
        uses: Hashnode-Action/Hashnode-Blog@v1
        with:
          hashnode_username: 'samikshakute'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Updated README with latest blog"
          git push

