name: "📚 Blog Updater"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */24 * * *' # Runs Every 24 Hours

jobs:
  update_blogs:
    name: "Update Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "Debugging: Check Input Values"
        run: |
          echo "USERNAME: samikshakute"
          echo "BLOG_URL: https://samikshakute.hashnode.dev"


      - name: "📚  Hashnode Updater"
        uses: "varunsridharan/action-hashnode-blog@1.2"
        with:
          USERNAME: 'samikshakute' # Hashnode Username
          COUNT: 1 # MAX Visisble
          STYLE: "blog-left"
          BLOG_URL: "https://samikshakute.hashnode.dev"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
